### ISSUE TITLE
generateCurves Creates an Empty Result

### ISSUE THREAD

**Issue by DarioS** [ellispatrick/lisaClust#9]
An list of `NULL`s is returned by a call to `generateCurves` function, so `lisa` function can't set row names on it.

```r
Browse[1]> head(cellSummary)
SplitDataFrameList of length 6
$`1`
DataFrame with 1625 rows and 6 columns
      imageID      cellID imageCellID         x         y               cellType
     <factor> <character> <character> <numeric> <numeric>            <character>
1           1 cell_358130         1_1    49.000   1.05263                  HER2+
2           1 cell_358131         1_2   345.000   3.92308         HR- CKlow CK5+
3           1 cell_358132         1_3    29.500   5.00000      Fibroblasts CD68+
4           1 cell_358133         1_4   291.192   4.88462 Macrophages Vim+ CD4..
5           1 cell_358134         1_5   261.254   4.29851 Macrophages Vim+ Slug+
...       ...         ...         ...       ...       ...                    ...
1621        1 cell_359750      1_1621   383.965   502.807 Macrophages Vim+ Slug-
1622        1 cell_359751      1_1622   304.675   502.725 Macrophages Vim+ CD4..
1623        1 cell_359752      1_1623   404.263   501.800          Myoepithelial
1624        1 cell_359753      1_1624   464.870   502.522 Macrophages Vim+ Slug-
1625        1 cell_359754      1_1625   394.486   502.486          Myoepithelial

...
<5 more elements>
Browse[1]> fast
  FALSE
Browse[1]> str(generateCurves)
function (data, Rs, window, window.length, BPcellType = BPcellType, sigma = sigma, ...)  
Browse[1]> Rs
  20  50 100
Browse[1]> window
  "convex"
Browse[1]> window.length
NULL
Browse[1]> sigma
  50
Browse[1]> curveList <- BiocParallel::bplapply(cellSummary, generateCurves, 
        Rs = Rs, window = window, window.length = window.length, 
        BPcellType = BPcellType, BPPARAM = BPimage, sigma = sigma)
Browse[1]> head(curveList, 3)
$`1`
NULL
$`3`
NULL
$`4`
NULL

Browse[1]>   rownames(curves) <- as.character(unlist(lapply(cellSummary, function(x) x$cellID)))
  Error in dimnames(x) <- dn: length of 'dimnames' [1] not equal to array extent
```

Traceback.

```
1: lisaClust(IMC, k = 10, sigma = 50, BPPARAM = MulticoreParam(16), fast = FALSE, 
2: lisa(cd, Rs = Rs, BPPARAM = BPPARAM, window = window, window.length = window.le
3: `rownames<-`(`*tmp*`, value = as.character(unlist(lapply(cellSummary, function(
```

**Comment by ellispatrick** [comment]
Hi Dario,
Did you set fast = FALSE or is that the default? This needs to be depreciated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Dario Strbenac ***@***.***>
Sent: Monday, July 29, 2024 6:00:32 PM
To: SydneyBioX/lisaClust ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SydneyBioX/lisaClust] generateCurves Creates an Empty Result (Issue #9)


An list of NULLs is returned by a call to generateCurves function, so lisa function can't set row names on it.

Browse[1]> head(cellSummary)
SplitDataFrameList of length 6
$`1`
DataFrame with 1625 rows and 6 columns
      imageID      cellID imageCellID         x         y               cellType
     <factor> <character> <character> <numeric> <numeric>            <character>
1           1 cell_358130         1_1    49.000   1.05263                  HER2+
2           1 cell_358131         1_2   345.000   3.92308         HR- CKlow CK5+
3           1 cell_358132         1_3    29.500   5.00000      Fibroblasts CD68+
4           1 cell_358133         1_4   291.192   4.88462 Macrophages Vim+ CD4..
5           1 cell_358134         1_5   261.254   4.29851 Macrophages Vim+ Slug+
...       ...         ...         ...       ...       ...                    ...
1621        1 cell_359750      1_1621   383.965   502.807 Macrophages Vim+ Slug-
1622        1 cell_359751      1_1622   304.675   502.725 Macrophages Vim+ CD4..
1623        1 cell_359752      1_1623   404.263   501.800          Myoepithelial
1624        1 cell_359753      1_1624   464.870   502.522 Macrophages Vim+ Slug-
1625        1 cell_359754      1_1625   394.486   502.486          Myoepithelial

...
<5 more elements>
Browse[1]> fast
  FALSE
Browse[1]> str(generateCurves)
function (data, Rs, window, window.length, BPcellType = BPcellType, sigma = sigma, ...)
Browse[1]> Rs
  20  50 100
Browse[1]> window
  "convex"
Browse[1]> window.length
NULL
Browse[1]> sigma
  50
Browse[1]> curveList <- BiocParallel::bplapply(cellSummary, generateCurves,
        Rs = Rs, window = window, window.length = window.length,
        BPcellType = BPcellType, BPPARAM = BPimage, sigma = sigma)
Browse[1]> head(curveList, 3)
$`1`
NULL
$`3`
NULL
$`4`
NULL

Browse[1]>   rownames(curves) <- as.character(unlist(lapply(cellSummary, function(x) x$cellID)))
  Error in dimnames(x) <- dn: length of 'dimnames' [1] not equal to array extent

Traceback.

1: lisaClust(IMC, k = 10, sigma = 50, BPPARAM = MulticoreParam(16), fast = FALSE,
2: lisa(cd, Rs = Rs, BPPARAM = BPPARAM, window = window, window.length = window.le
3: `rownames<-`(`*tmp*`, value = as.character(unlist(lapply(cellSummary, function(

**Comment by DarioS** [comment]
I chose it but I shall leave it at default in future until it is made defunct.
